env: lfc
component: app
componentType: server

serviceAccount:
  create: false
  name: "default"

ports:
  - name: http
    protocol: TCP
    servicePort: 3000
    containerPort: 3000

ingress:
  port: 3000

deployment:
  customNodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: eks.amazonaws.com/capacityType
              operator: In
              values:
                - ON_DEMAND

  replicaCount: 1

  terminationGracePeriodSeconds: 300

  resources:
    requests:
      cpu: 100m
      memory: 100Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
